on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.1'

      - name: compile
        env:
          GO111MODULE: auto
        run: |
          go run build/ci.go install ./cmd/geth
          strip build/bin/geth
          mv build/bin/geth build/bin/geth-linux-amd64

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: build/bin/geth-linux-amd64

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set some variables for the image
        run: |
          echo "IMAGE_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            elhereum/go-elh:latest
            elhereum/go-elh:${{ env.IMAGE_VERSION }}
